"""
Workforce OS — Hierarchical Formatter
Transforms raw agent responses into structured executive output.

Format: Summary → Perspectives → Devil's Advocate → Sources
"""

from typing import List, Dict, Any
from datetime import datetime
from jinja2 import Template

# ═══════════════════════════════════════════════════════════════════════════
# Templates
# ═══════════════════════════════════════════════════════════════════════════

COUNCIL_TEMPLATE = Template("""\
📋 CONSELHO EXECUTIVO
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Pergunta:** {{ question }}
**Data:** {{ date }}
**Especialistas consultados:** {{ agents }}

---

## Sumário Executivo

{{ summary }}

---

## Perspectivas

{% for p in perspectives %}
### {{ p.agent }}
{{ p.content }}

{% endfor %}
---

## Advogado do Diabo

{% for d in devils_advocate %}
> ⚠️ {{ d }}
{% endfor %}

---

## Fontes

{% for s in sources %}
- **{{ s.agent }}**: {{ s.source }}
{% endfor %}

---

*Conselho gerado pelo Second Brain. Use como insumo para sua decisão, não como decisão final.*
""")

GROUP_TEMPLATE = Template("""\
🗣️ DEBATE DO GRUPO EXECUTIVO
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Tópico:** {{ topic }}
**Participantes:** {{ participants }}
**Rounds:** {{ rounds }}

---

## Debate

{% for turn in turns %}
### {{ turn.name }} (Round {{ turn.round }})

{{ turn.content }}

{% endfor %}
---

## Consenso

{{ consensus }}

---

## Divergências

{% for d in divergences %}
- **{{ d.agent }}**: {{ d.point }}
{% endfor %}
""")

PING_TEMPLATE = Template("""\
🌅 BRIEFING DIÁRIO — {{ date }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Setor:** {{ sector }}

---

## Mercado

{% for item in market %}
- {{ item }}
{% endfor %}

---

## Seu Setor

{% for item in sector_news %}
- {{ item }}
{% endfor %}

---

## Alerta

{% for item in alerts %}
- ⚠️ {{ item }}
{% endfor %}

---

*Briefing gerado às {{ time }}. Aprofunde qualquer item iniciando uma conversa.*
""")


class HierarchicalFormatter:
    """Formats raw agent responses into structured executive output."""
    
    async def format_council(
        self,
        question: str,
        responses: List[Dict[str, Any]],
        summary: str = "",
    ) -> Dict[str, Any]:
        """
        Format a council session response.
        
        Args:
            question: Original question
            responses: List of {agent, name, content} dicts
            summary: Optional executive summary (generated by LLM)
        """
        now = datetime.now()
        
        if not summary:
            summary = self._extract_summary(responses)
        
        html = COUNCIL_TEMPLATE.render(
            question=question,
            date=now.strftime("%d/%m/%Y às %H:%M"),
            agents=", ".join(r.get("name", r.get("agent", "")) for r in responses),
            summary=summary,
            perspectives=[
                {
                    "agent": r.get("name", r.get("agent", "")),
                    "content": r.get("content", ""),
                }
                for r in responses
            ],
            devils_advocate=self._extract_devils_advocate(responses),
            sources=[
                {
                    "agent": r.get("name", r.get("agent", "")),
                    "source": r.get("source", "Knowledge base do agente"),
                }
                for r in responses
            ],
        )
        
        return {
            "question": question,
            "summary": summary,
            "perspectives": responses,
            "devils_advocate": self._extract_devils_advocate(responses),
            "html": html,
            "markdown": html,
        }
    
    async def format_group(
        self,
        topic: str,
        debate: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Format a group debate result."""
        turns = debate.get("turns", [])
        consensus = debate.get("consensus", "Não houve consenso claro.")
        
        return {
            "topic": topic,
            "turns": turns,
            "consensus": consensus,
            "divergences": debate.get("divergences", []),
            "html": GROUP_TEMPLATE.render(
                topic=topic,
                participants=", ".join(set(t.get("name", "") for t in turns)),
                rounds=debate.get("rounds", len(turns)),
                turns=turns,
                consensus=consensus,
                divergences=debate.get("divergences", []),
            ),
        }
    
    async def format_ping(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Format a daily briefing."""
        now = datetime.now()
        sector = data.get("sector", "Geral")
        
        return {
            "sector": sector,
            "market": data.get("market", []),
            "sector_news": data.get("sector_news", []),
            "alerts": data.get("alerts", []),
            "html": PING_TEMPLATE.render(
                date=now.strftime("%d/%m/%Y"),
                time=now.strftime("%H:%M"),
                sector=sector,
                market=data.get("market", []),
                sector_news=data.get("sector_news", []),
                alerts=data.get("alerts", []),
            ),
        }
    
    # ── Private helpers ─────────────────────────────────────────────────
    
    def _extract_summary(self, responses: List[Dict[str, Any]]) -> str:
        """Extract or generate executive summary."""
        contents = [r.get("content", "") for r in responses if r.get("content")]
        if not contents:
            return "Análise indisponível."
        # Simple: first 1-2 sentences of the highest-confidence response
        first = contents[0].split(".")[:2]
        return ". ".join(first).strip() + "."
    
    def _extract_devils_advocate(self, responses: List[Dict[str, Any]]) -> List[str]:
        """Extract contrarian points."""
        points = []
        for r in responses:
            content = r.get("content", "")
            # Look for risk/disagreement language
            for marker in ["risco", "atenção", "cuidado", "porém", "entretanto"]:
                if marker in content.lower():
                    # Extract the sentence containing the marker
                    sentences = content.split(".")
                    for s in sentences:
                        if marker in s.lower():
                            points.append(s.strip())
                            break
        return points[:3]  # Max 3 devil's advocate points
