-- ============================================================================
-- ⚠️  THIS FILE IS A REFERENCE STUB — NOT A LIVE MIGRATION
-- ============================================================================
--
-- The Workforce OS motor shares its Postgres schema with the Febrain
-- Supabase project (ref: ftlzbhmjjtetrchfcxtv). The real schema is much
-- richer than this file (35+ columns on personas, full lifecycle/eval
-- framework, dynamic_agents, twin/synthetic_personas, langgraph_*, etc).
--
-- DO NOT RUN this against an empty Supabase project — it will give you a
-- broken, partial copy of the real schema and the application code will
-- not work against it (e.g. match_personas RPC signature, status column,
-- embedding dimensions all differ from what's below).
--
-- Authoritative sources:
--   • Production schema  →  Supabase project `syntheticperson` (ftlzbhmjjtetrchfcxtv)
--   • Migration history  →  Febrain repo, supabase/migrations/
--   • Edge functions     →  Febrain repo, supabase/functions/
--                           (workforce-os ships its own under
--                            workforce-os/supabase/functions/)
--
-- See FORK.md at the repo root for the plan to consolidate the motor
-- (Council + Lifecycle + Dynamic Agents + Synthetic Personas) into
-- this repository as the new owner. Twins remain in Febrain as a
-- separate product.
-- ============================================================================
